### ISSUE TITLE
where can i get the dataset of this project

### ISSUE THREAD

**Issue by ZdayAlster** [ankile/defi-measurement#1]
It's a great project, And helpful for me .
Where can i get the data of this project, or how to get the data, that can be used in this project!!

Thanks!!

**Comment by ZdayAlster** [comment]
Got it, Thanks!!

**Comment by ankile** [comment]
Hey, I'm so sorry this took a while.

I took the main code for [the paper](https://openreview.net/pdf?id=0O5vbRAWol) and moved it to a new repo that's cleaned up with only the relevant code: [https://github.com/ankile/surveillance-metric](https://github.com/ankile/surveillance-metric).

I have instructions for how to download the data there as well. Hopefully, that helps!

Best, Lars
